### ISSUE TITLE
GitHub Pages が公開されない

### ISSUE THREAD

**Issue by kurokobo** [momosk-dt/Piper-for-Partner-2020#3]
`gh-pages` ブランチにラボガイドをコミットしたのですが、公開されないようです。

お手数ですが、このプロジェクトの `Settings` ページの下の方にある **GitHub Pages** のセクションの設定を確認いただいてもよいでしょうか。

以下は例ですが、`Source` が `gh-pages` ブランチの `/` な状態が期待値です。

![image](https://user-images.githubusercontent.com/2920259/99187895-9f8afe80-279c-11eb-8082-5bb5157a2d7f.png)

自分のリポジトリ下での公開でも構わないので、解決必須ではないです。

**Comment by momosk-dt** [comment]
セクションの設定をしてみました。どうでしょうか？

**Comment by kurokobo** [comment]
ありがとうございます！ アクセス確認できました。

* https://momosk-dt.github.io/Piper-for-Partner-2020/Module10/

クローズしますね。ありがとうございました。
